# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # Supports pyproject.toml, requirements.txt, setup.py, etc.
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    # Optional: Group updates to reduce PR noise
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff*"
          - "mypy*"
          - "pre-commit*"
          - "types-*"
      production-dependencies:
        patterns:
          - "requests*"
          - "python-dotenv*"
          - "click*"
